// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Data;

#nullable disable

namespace TechStore.Migrations
{
    [DbContext(typeof(TechStoreContext))]
    [Migration("20261003023138_AgregarDescripcionCategoriaYDatosIniciales")]
    partial class AgregarDescripcionCategoriaYDatosIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Smartphones de última generación.",
                            Nombre = "Celulares"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "GPUs para gaming y trabajo profesional.",
                            Nombre = "Tarjetas de video"
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Consolas de videojuegos de sobremesa y portátiles.",
                            Nombre = "Consolas"
                        },
                        new
                        {
                            ID = 4,
                            Descripcion = "Auriculares, parlantes y accesorios de sonido.",
                            Nombre = "Audio"
                        },
                        new
                        {
                            ID = 5,
                            Descripcion = "Laptops para estudio, trabajo y gaming.",
                            Nombre = "Notebooks"
                        },
                        new
                        {
                            ID = 6,
                            Descripcion = "Tablets para productividad y entretenimiento.",
                            Nombre = "Tablets"
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoriaId = 1,
                            Descripcion = "Diseño revolucionario en aluminio de grado aeroespacial, impulsado por el nuevo chip A18 para un rendimiento ultrarrápido y máxima eficiencia.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/iphone_16.jpg",
                            Nombre = "IPhone 16",
                            Precio = 1250m,
                            Stock = 10
                        },
                        new
                        {
                            ID = 2,
                            CategoriaId = 2,
                            Descripcion = "Lleva tu experiencia visual al extremo. Diseñada bajo la avanzada arquitectura NVIDIA Blackwell y respaldada por 16 GB de memoria ultra rápida GDDR7.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/asus_prime_rtx_5080.jpg",
                            Nombre = "Asus Prime RTX 5080",
                            Precio = 1500m,
                            Stock = 16
                        },
                        new
                        {
                            ID = 3,
                            CategoriaId = 3,
                            Descripcion = "Consola portátil de videojuegos con pantalla OLED de colores vibrantes, negros puros y una batería de mayor duración.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/steam_deck.jpg",
                            Nombre = "Steam Deck OLED",
                            Precio = 980.65m,
                            Stock = 4
                        },
                        new
                        {
                            ID = 4,
                            CategoriaId = 4,
                            Descripcion = "Auriculares inalámbricos de gama alta con la cancelación de ruido activa líder de la industria y un perfil de sonido de alta definición.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/sony_wh1000xm6.jpg",
                            Nombre = "Sony WH-1000XM6",
                            Precio = 340m,
                            Stock = 8
                        },
                        new
                        {
                            ID = 5,
                            CategoriaId = 5,
                            Descripcion = "La laptop más potente de Apple, con el chip M3 Pro y una pantalla Retina de 16 pulgadas.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/macbookpro.jpg",
                            Nombre = "MacBook Pro 16\"",
                            Precio = 2499m,
                            Stock = 6
                        },
                        new
                        {
                            ID = 6,
                            CategoriaId = 6,
                            Descripcion = "La tablet más rápida de Apple, con el chip M1 y una pantalla Liquid Retina de 10.9 pulgadas.",
                            Estado = "Disponible",
                            ImagenUrl = "/images/airpadair.jpg",
                            Nombre = "iPad Air",
                            Precio = 599m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.HasOne("TechStore.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
